name: CI

on:
  pull_request:
    branches: [ develop, main ]

jobs:
  check-php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: PHP Syntax Check
        run: find . -name '*.php' -exec php -l {} \;
